name: Structural Time Series
description: California electricity demand forecasting with Prophet.
author: Cloudera Engineer
specification_version: 1.0
prototype_version: 1.0
date: "2020-10-14"
api_version: 1

environment_variables:
  EIA_API_KEY:
    default: "SUPER AWESOME EIA KEY"
    description: "EIA open data API key"
    prompt_user: false

tasks:
  - type: start_application
    name: Diagnostic app
    subdomain: diagnostics
    script: apps/launch_diagnostics.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3
    
  - type: start_application
    name: Forecast app
    subdomain: forecast
    script: apps/launch_forecast.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3